version: '3.5'

volumes:
    nginx_certs:
    nginx_vhost.d:
    nginx_html:
    nginx_dhparam:

networks:
  nginx-proxy-network:
    name: nginx-proxy-network

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_certs:/etc/nginx/certs:ro
      - nginx_vhost.d:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - nginx_dhparam:/etc/nginx/dhparam
      - ./custom-nginx-config.conf:/etc/nginx/conf.d/custom-nginx-config.conf
    networks:
      - nginx-proxy-network

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx_certs:/etc/nginx/certs:rw
      - nginx_vhost.d:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - nginx_dhparam:/etc/nginx/dhparam
    networks:
      - nginx-proxy-network
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy